sudo: required
services:
    - docker

before_install:
    - docker build -t jcgp99/docker -f Dockerfile.dev .

script:
    - docker run -e CI=true jcgp99/docker npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "us-east-2" 
    app: "docker-test"
    env: "Docker-test-env"
    bucket_name: "elasticbeanstalk-us-east-2-156986300813" 
    bucket_path: "docker-test"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY